# Generated by Django 5.2.7 on 2025-11-18 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id_disponibilidade', models.AutoField(db_column='id_disponibilidade', primary_key=True, serialize=False)),
                ('data', models.DateField(db_column='data')),
                ('hora_inicio', models.TimeField(db_column='hora_inicio')),
                ('hora_fim', models.TimeField(db_column='hora_fim')),
                ('duracao_slot', models.IntegerField(db_column='duracao_slot')),
                ('status_slot', models.CharField(db_column='status_slot', max_length=20)),
            ],
            options={
                'db_table': '"DISPONIBILIDADE"',
            },
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id_especialidade', models.AutoField(db_column='id_especialidade', primary_key=True, serialize=False)),
                ('nome_especialidade', models.CharField(db_column='nome_especialidade', max_length=255)),
                ('descricao', models.CharField(blank=True, db_column='descricao', max_length=255, null=True)),
            ],
            options={
                'db_table': '"ESPECIALIDADES"',
            },
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id_regiao', models.AutoField(db_column='id_regiao', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nome', max_length=50)),
                ('tipo_regiao', models.CharField(db_column='tipo_regiao', max_length=50)),
            ],
            options={
                'db_table': '"REGIAO"',
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_utilizador', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('n_utente', models.CharField(blank=True, max_length=20, null=True)),
                ('senha', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=20)),
                ('data_registo', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('foto_perfil', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(db_column='id_consulta', primary_key=True, serialize=False)),
                ('data_consulta', models.DateField(db_column='data_consulta')),
                ('hora_consulta', models.TimeField(db_column='hora_consulta')),
                ('estado', models.CharField(db_column='estado', max_length=50)),
                ('motivo', models.CharField(blank=True, db_column='motivo', max_length=255, null=True)),
                ('id_disponibilidade', models.ForeignKey(db_column='id_disponibilidade', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.disponibilidade')),
            ],
            options={
                'db_table': '"CONSULTAS"',
            },
        ),
        migrations.CreateModel(
            name='Enfermeiro',
            fields=[
                ('id_enfermeiro', models.AutoField(db_column='id_enfermeiro', primary_key=True, serialize=False)),
                ('n_ordem_enf', models.CharField(db_column='n_ordem_enf', max_length=50)),
                ('id_utilizador', models.ForeignKey(db_column='id_utilizador', on_delete=django.db.models.deletion.CASCADE, related_name='enfermeiros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"ENFERMEIRO"',
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id_fatura', models.AutoField(db_column='id_fatura', primary_key=True, serialize=False)),
                ('valor', models.DecimalField(db_column='valor', decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.CharField(db_column='metodo_pagamento', max_length=50)),
                ('estado', models.CharField(db_column='estado', max_length=50)),
                ('data_pagamento', models.DateField(blank=True, db_column='data_pagamento', null=True)),
                ('id_consulta', models.ForeignKey(db_column='id_consulta', on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='core.consulta')),
            ],
            options={
                'db_table': '"FATURAS"',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(db_column='id_medico', primary_key=True, serialize=False)),
                ('numero_ordem', models.CharField(db_column='numero_ordem', max_length=50)),
                ('id_especialidade', models.ForeignKey(blank=True, db_column='id_especialidade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos', to='core.especialidade')),
                ('id_utilizador', models.ForeignKey(db_column='id_utilizador', on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"MEDICOS"',
            },
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='id_medico',
            field=models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='core.medico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='id_medico',
            field=models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.medico'),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(db_column='id_paciente', primary_key=True, serialize=False)),
                ('data_nasc', models.DateField(db_column='data_nasc')),
                ('genero', models.CharField(db_column='genero', max_length=50)),
                ('morada', models.CharField(blank=True, db_column='morada', max_length=255, null=True)),
                ('alergias', models.CharField(blank=True, db_column='alergias', max_length=255, null=True)),
                ('observacoes', models.CharField(blank=True, db_column='observacoes', max_length=255, null=True)),
                ('id_utilizador', models.ForeignKey(db_column='id_utilizador', on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"PACIENTES"',
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.paciente'),
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id_receita', models.AutoField(db_column='id_receita', primary_key=True, serialize=False)),
                ('medicamento', models.CharField(db_column='medicamento', max_length=255)),
                ('dosagem', models.CharField(db_column='dosagem', max_length=255)),
                ('instrucoes', models.CharField(blank=True, db_column='instrucoes', max_length=255, null=True)),
                ('data_prescricao', models.DateField(db_column='data_prescricao')),
                ('id_consulta', models.ForeignKey(db_column='id_consulta', on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='core.consulta')),
            ],
            options={
                'db_table': '"RECEITAS"',
            },
        ),
        migrations.CreateModel(
            name='UnidadeSaude',
            fields=[
                ('id_unidade', models.AutoField(db_column='id_unidade', primary_key=True, serialize=False)),
                ('nome_unidade', models.CharField(db_column='nome_unidade', max_length=255)),
                ('morada_unidade', models.CharField(db_column='morada_unidade', max_length=255)),
                ('tipo_unidade', models.CharField(db_column='tipo_unidade', max_length=255)),
                ('id_regiao', models.ForeignKey(db_column='id_regiao', on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='core.regiao')),
            ],
            options={
                'db_table': '"UNIDADE_DE_SAUDE"',
            },
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='id_unidade',
            field=models.ForeignKey(db_column='id_unidade', on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='core.unidadesaude'),
        ),
    ]
