# Generated by Django 5.2.7 on 2025-11-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='utilizador',
            table='"UTILIZADOR"',
        ),
    ]
