# Generated by Django 5.2.7 on 2025-11-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_utilizador_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='utilizador',
            table=None,
        ),
    ]
