# Generated by Django 5.2.7 on 2025-11-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_utilizador_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='role',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('medico', 'Médico'), ('enfermeiro', 'Enfermeiro'), ('admin', 'Administrador')], default='paciente', max_length=20),
        ),
        migrations.AlterModelTable(
            name='utilizador',
            table=None,
        ),
    ]
