# Generated by Django 5.1.4 on 2026-01-06 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_utilizador_role_alter_utilizador_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='medico_aceitou',
            field=models.BooleanField(db_column='medico_aceitou', default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente_aceitou',
            field=models.BooleanField(db_column='paciente_aceitou', default=False),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='id_disponibilidade',
            field=models.ForeignKey(blank=True, db_column='id_disponibilidade', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.disponibilidade'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='id_medico',
            field=models.ForeignKey(blank=True, db_column='id_medico', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.medico'),
        ),
    ]
