# Generated by Django 5.1.4 on 2026-01-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_consulta_medico_aceitou_consulta_paciente_aceitou_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='email_verified',
            field=models.BooleanField(db_column='email_verified', default=False),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='reset_token',
            field=models.CharField(blank=True, db_column='reset_token', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, db_column='reset_token_expires', null=True),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='verification_token',
            field=models.CharField(blank=True, db_column='verification_token', max_length=100, null=True),
        ),
    ]
