# Generated by Django 5.1.4 on 2026-01-08 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_utilizador_email_verified_utilizador_reset_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(db_column='id_horario', primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], db_column='dia_semana')),
                ('hora_inicio', models.TimeField(db_column='hora_inicio')),
                ('hora_fim', models.TimeField(db_column='hora_fim')),
                ('duracao_slot', models.IntegerField(db_column='duracao_slot', default=30, help_text='Duração da consulta em minutos')),
                ('ativo', models.BooleanField(db_column='ativo', default=True)),
                ('data_inicio_vigencia', models.DateField(blank=True, db_column='data_inicio_vigencia', help_text='Início da vigência deste horário', null=True)),
                ('data_fim_vigencia', models.DateField(blank=True, db_column='data_fim_vigencia', help_text='Fim da vigência deste horário', null=True)),
                ('id_medico', models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.medico')),
                ('id_unidade', models.ForeignKey(db_column='id_unidade', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.unidadesaude')),
            ],
            options={
                'db_table': '"HORARIO"',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Indisponibilidade',
            fields=[
                ('id_indisponibilidade', models.AutoField(db_column='id_indisponibilidade', primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(db_column='data_inicio')),
                ('data_fim', models.DateField(db_column='data_fim')),
                ('tipo', models.CharField(choices=[('ferias', 'Férias'), ('formacao', 'Formação'), ('doenca', 'Doença'), ('outro', 'Outro')], db_column='tipo', default='ferias', max_length=20)),
                ('motivo', models.CharField(blank=True, db_column='motivo', max_length=255, null=True)),
                ('todo_dia', models.BooleanField(db_column='todo_dia', default=True, help_text='Se False, aplicar apenas às horas específicas')),
                ('hora_inicio', models.TimeField(blank=True, db_column='hora_inicio', null=True)),
                ('hora_fim', models.TimeField(blank=True, db_column='hora_fim', null=True)),
                ('id_medico', models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilidades', to='core.medico')),
            ],
            options={
                'db_table': '"INDISPONIBILIDADE"',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id_lista_espera', models.AutoField(db_column='id_lista_espera', primary_key=True, serialize=False)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, db_column='data_inscricao')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], db_column='prioridade', default='normal', max_length=20)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('notificado', 'Notificado'), ('agendado', 'Agendado'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], db_column='status', default='aguardando', max_length=20)),
                ('motivo', models.TextField(blank=True, db_column='motivo', null=True)),
                ('observacoes', models.TextField(blank=True, db_column='observacoes', null=True)),
                ('data_notificacao', models.DateTimeField(blank=True, db_column='data_notificacao', null=True)),
                ('data_agendamento', models.DateTimeField(blank=True, db_column='data_agendamento', null=True)),
                ('id_consulta', models.ForeignKey(blank=True, db_column='id_consulta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lista_espera', to='core.consulta')),
                ('id_especialidade', models.ForeignKey(db_column='id_especialidade', on_delete=django.db.models.deletion.CASCADE, related_name='listas_espera', to='core.especialidade')),
                ('id_medico', models.ForeignKey(blank=True, db_column='id_medico', help_text='Médico específico (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas_espera', to='core.medico')),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, related_name='listas_espera', to='core.paciente')),
                ('id_unidade', models.ForeignKey(blank=True, db_column='id_unidade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas_espera', to='core.unidadesaude')),
            ],
            options={
                'db_table': '"LISTA_ESPERA"',
                'ordering': ['data_inscricao'],
            },
        ),
    ]
