# Generated by Django 5.1.4 on 2026-01-08 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_utilizador_email_verified_utilizador_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Indisponibilidade',
            fields=[
                ('id_indisponibilidade', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, help_text='Deixe vazio para dia completo', null=True)),
                ('hora_fim', models.TimeField(blank=True, help_text='Deixe vazio para dia completo', null=True)),
                ('tipo', models.CharField(choices=[('ferias', 'Férias'), ('ausencia', 'Ausência'), ('formacao', 'Formação'), ('doenca', 'Doença'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(db_column='ID_MEDICO', on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilidades', to='core.medico')),
            ],
            options={
                'db_table': '"INDISPONIBILIDADES"',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id_lista_espera', models.AutoField(primary_key=True, serialize=False)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Normal'), (3, 'Alta'), (4, 'Urgente')], default=2)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('notificado', 'Notificado'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('data_notificacao', models.DateTimeField(blank=True, null=True)),
                ('consulta', models.ForeignKey(blank=True, db_column='ID_CONSULTA', help_text='Consulta agendada após notificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lista_espera', to='core.consulta')),
                ('especialidade', models.ForeignKey(db_column='ID_ESPECIALIDADE', on_delete=django.db.models.deletion.CASCADE, related_name='listas_espera', to='core.especialidade')),
                ('paciente', models.ForeignKey(db_column='ID_PACIENTE', on_delete=django.db.models.deletion.CASCADE, related_name='listas_espera', to='core.paciente')),
                ('unidade', models.ForeignKey(blank=True, db_column='ID_UNIDADE', help_text='Unidade preferencial (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas_espera', to='core.unidadesaude')),
            ],
            options={
                'db_table': '"LISTAS_ESPERA"',
                'ordering': ['-prioridade', 'data_inscricao'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='Dia da semana (0=Segunda, 6=Domingo)')),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('duracao_slot', models.IntegerField(default=30, help_text='Duração de cada slot em minutos')),
                ('data_inicio', models.DateField(help_text='Data a partir da qual este horário é válido')),
                ('data_fim', models.DateField(blank=True, help_text='Data até a qual este horário é válido (deixe vazio para sem limite)', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(db_column='ID_MEDICO', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.medico')),
                ('unidade', models.ForeignKey(db_column='ID_UNIDADE', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.unidadesaude')),
            ],
            options={
                'db_table': '"HORARIOS"',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('medico', 'unidade', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
