# Generated by Django 5.2.7 on 2026-01-09 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_utilizador_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_column='criado_em', null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consulta',
            name='hora_checkin',
            field=models.DateTimeField(blank=True, db_column='hora_checkin', null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='hora_fim_real',
            field=models.DateTimeField(blank=True, db_column='hora_fim_real', help_text='Hora real de término', null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='hora_inicio_real',
            field=models.DateTimeField(blank=True, db_column='hora_inicio_real', help_text='Hora real de início', null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='link_chamada',
            field=models.URLField(blank=True, db_column='link_chamada', help_text='Link para videochamada', null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True, db_column='modificado_em', null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='modificado_por',
            field=models.ForeignKey(blank=True, db_column='modificado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consulta',
            name='notas_clinicas',
            field=models.TextField(blank=True, db_column='notas_clinicas', help_text='Resumo clínico da consulta', null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='observacoes',
            field=models.TextField(blank=True, db_column='observacoes', help_text='Observações adicionais', null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente_presente',
            field=models.BooleanField(db_column='paciente_presente', default=False, help_text='Check-in realizado'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tipo_consulta',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('teleconsulta', 'Teleconsulta')], db_column='tipo_consulta', default='presencial', max_length=20),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_avaliacao', models.AutoField(db_column='id_avaliacao', primary_key=True, serialize=False)),
                ('classificacao', models.IntegerField(choices=[(1, '1 Estrela'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')], db_column='classificacao', help_text='Classificação de 1 a 5 estrelas')),
                ('comentario', models.TextField(blank=True, db_column='comentario', null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True, db_column='data_avaliacao')),
                ('id_consulta', models.OneToOneField(db_column='id_consulta', on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='core.consulta')),
            ],
            options={
                'db_table': '"AVALIACOES"',
            },
        ),
    ]
