# Generated by Django 5.2.7 on 2026-01-09 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_consulta_criado_em_consulta_criado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='link_chamada',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='tipo_consulta',
        ),
    ]
