# Generated by Django 5.1.4 on 2026-01-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_consulta_link_chamada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='senha',
        ),
    ]
