# Generated by Django 5.1.4 on 2026-01-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_senha_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='horario',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='indisponibilidade',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='listaespera',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='listaespera',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='listaespera',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='listaespera',
            name='unidade',
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='Indisponibilidade',
        ),
        migrations.DeleteModel(
            name='ListaEspera',
        ),
    ]
